# Generated by Django 5.2 on 2026-08-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration',
            field=models.CharField(blank=True, help_text='Actual Duration', max_length=10, null=True),
        ),
    ]
