# Generated by Django 5.2 on 2026-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0002_alter_media_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
