# Generated by Django 5.2 on 2026-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_room_accent_room_icon_discussion_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='handle',
            field=models.CharField(max_length=20),
        ),
    ]
