# Generated by Django 5.2 on 2026-07-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_alter_message_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='buried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='off_topic_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MessageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('action', models.CharField(choices=[('off_topic', 'Off Topic'), ('ruins_room', 'Ruins Room')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='connect.message')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('message', 'handle', 'action'), name='unique_action_per_handle')],
            },
        ),
    ]
