# Generated by Django 5.2 on 2026-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_message_buried_message_off_topic_hidden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageaction',
            name='action',
            field=models.CharField(choices=[('off_topic', 'Off Topic'), ('bury', 'Bury')], max_length=20),
        ),
    ]
