# Generated by Django 5.2 on 2026-07-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_alter_messageaction_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
