# Generated by Django 5.2 on 2026-07-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_message_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=50)),
                ('reaction', models.CharField(choices=[('true', 'True'), ('false', 'False'), ('valid', 'Valid'), ('yikes', 'Yikes'), ('nice', 'Nice')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='connect.message')),
            ],
            options={
                'unique_together': {('message', 'handle')},
            },
        ),
    ]
