# Generated by Django 5.2 on 2026-07-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_messagereaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereaction',
            name='reaction',
            field=models.CharField(choices=[('valid', 'Valid'), ('props', 'Props'), ('yikes', 'Yikes'), ('sus', 'Sus'), ('nope', 'Nope')], max_length=20),
        ),
    ]
