# Generated by Django 5.2 on 2025-09-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0005_alter_category_options_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
