# Generated by Django 5.2 on 2025-09-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0007_post_subcategory_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_plain_text',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Admin', max_length=40),
        ),
        migrations.AddField(
            model_name='post',
            name='content_JSON',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
