# Generated by Django 5.2 on 2025-09-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0011_alter_post_author_alter_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_plain_text',
            field=models.TextField(blank=True),
        ),
    ]
