# Generated by Django 5.2 on 2025-09-26 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0013_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postimage',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PostLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('affiliate', 'Affiliate'), ('reference', 'Reference')], default='reference', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='codedly.post')),
                ('target_post', models.ForeignKey(blank=True, help_text='Optional: link to another post internally', null=True, on_delete=django.db.models.deletion.SET_NULL, to='codedly.post')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
