# Generated by Django 5.2 on 2025-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0014_alter_postimage_options_postimage_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlink',
            name='url',
        ),
        migrations.AddField(
            model_name='postlink',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
