# Generated by Django 5.2 on 2025-09-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0015_remove_postlink_url_postlink_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
