# Generated by Django 5.2 on 2025-09-30 18:58

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0017_course_lesson_lessonresource'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
