# Generated by Django 5.2 on 2025-10-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0018_course_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='meta',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
