# Generated by Django 5.2 on 2025-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0019_course_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta',
            field=models.CharField(blank=True, max_length=170),
        ),
    ]
