# Generated by Django 5.2 on 2025-10-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0020_alter_course_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
