# Generated by Django 5.2 on 2025-10-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0022_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
