# Generated by Django 5.2 on 2025-10-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0024_lesson_created_at_lesson_duration_lesson_is_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.CharField(default='Basic computer literacy', max_length=255),
        ),
    ]
