# Generated by Django 5.2 on 2025-10-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0025_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
