# Generated by Django 5.2 on 2025-10-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0026_course_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_plain_text',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
