# Generated by Django 5.2 on 2025-10-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0028_alter_category_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='difficulty',
            new_name='level',
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
