# Generated by Django 5.2 on 2025-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0029_rename_difficulty_course_level_lesson_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_plain_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
