# Generated by Django 5.2 on 2025-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0030_alter_lesson_content_plain_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
