# Generated by Django 5.2 on 2025-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0031_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
