# Generated by Django 5.2 on 2025-10-04 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0032_alter_lesson_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id']},
        ),
    ]
