# Generated by Django 5.2 on 2025-10-09 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0033_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='content_json',
            new_name='content_JSON',
        ),
    ]
