# Generated by Django 5.2 on 2025-10-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0034_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['course', 'order']},
        ),
    ]
