# Generated by Django 5.2 on 2025-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0035_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
