# Generated by Django 5.2 on 2025-10-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0036_alter_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('React', 'React')], max_length=50),
        ),
    ]
