# Generated by Django 5.2 on 2025-10-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0037_alter_course_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
