# Generated by Django 5.2 on 2025-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0038_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='about',
            field=models.TextField(blank=True, help_text="Short 'About this' section for context.", null=True),
        ),
    ]
