# Generated by Django 5.2 on 2025-11-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0039_subcategory_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Python', 'Python'), ('JavaScript', 'JavaScript'), ('React', 'React')], max_length=50),
        ),
    ]
