# Generated by Django 5.2 on 2025-11-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0041_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sort',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
