# Generated by Django 5.2 on 2025-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0042_course_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/verycodedly/image/upload/v1763448383/very-codedly-banner.png', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
