# Generated by Django 5.2.8 on 2025-12-15 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0044_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
