# Generated by Django 5.2.8 on 2026-01-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0045_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Chrise', max_length=50),
        ),
    ]
