# Generated by Django 5.2.8 on 2026-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0047_alter_post_alt_alter_post_author_alter_post_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
