# Generated by Django 5.2.8 on 2026-03-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0049_rename_keywords_course_tags_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
