# Generated by Django 5.2.8 on 2026-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0051_storeorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('mug', 'Mug'), ('hat', 'Hat'), ('shirt', 'T-Shirt'), ('hoodie', 'Hoodie'), ('digital', 'Digital'), ('cheatsheet', 'Cheatsheet')], max_length=20)),
                ('details', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('pre_order', 'Pre-order'), ('sold_out', 'Sold Out')], default='published', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Product',
                'verbose_name_plural': 'Store Products',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
