# Generated by Django 5.2.8 on 2026-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0052_storeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
