# Generated by Django 5.2.8 on 2026-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0054_alter_storeproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
