# Generated by Django 5.2.8 on 2026-04-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0056_alter_storeproduct_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta',
            field=models.TextField(blank=True, max_length=170),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
