# Generated by Django 5.2.8 on 2026-04-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0057_alter_course_meta_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta',
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, db_index=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
