# Generated by Django 5.2.8 on 2026-04-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0058_alter_course_meta_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeproduct',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': 'Store Product', 'verbose_name_plural': 'Store Products'},
        ),
    ]
