# Generated by Django 5.2.8 on 2026-04-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0059_alter_storeproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='shipping_country',
            field=models.CharField(max_length=100),
        ),
    ]
