# Generated by Django 5.2.8 on 2026-04-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0060_alter_storeorder_shipping_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeorder',
            old_name='paystack_reference',
            new_name='payment_reference',
        ),
        migrations.RenameField(
            model_name='storeorder',
            old_name='paystack_response',
            new_name='payment_response',
        ),
        migrations.RenameField(
            model_name='storeorder',
            old_name='paystack_status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='storeorder',
            name='payment_gateway',
            field=models.CharField(default='flutterwave', max_length=20),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
