# Generated by Django 5.2.8 on 2026-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0061_rename_paystack_reference_storeorder_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintfulProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('printful_id', models.IntegerField(unique=True)),
                ('category', models.CharField(default='merch', max_length=50)),
                ('variant_mapping', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, help_text='Starting at price', max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
