# Generated by Django 5.2.8 on 2026-04-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0062_printfulproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printfulproducts',
            options={'ordering': ['created_at'], 'verbose_name': 'Printful Products', 'verbose_name_plural': 'Printful Products'},
        ),
        migrations.RemoveField(
            model_name='printfulproducts',
            name='tagline',
        ),
    ]
