# Generated by Django 5.2.8 on 2026-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0063_alter_printfulproducts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulproducts',
            name='fancy_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printfulproducts',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='printfulproducts',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printfulproducts',
            name='category',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('sweatshirts', 'Sweatshirts'), ('tshirts', 'T-Shirts'), ('hats', 'Hats'), ('mugs', 'Mugs'), ('bottles', 'Bottles'), ('workspace', 'Workspace'), ('totes', 'Totes'), ('mini_dev', 'Mini Dev'), ('accessories', 'Accessories')], default='accessories', max_length=50),
        ),
        migrations.AlterField(
            model_name='printfulproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Starting price', max_digits=10),
        ),
    ]
