# Generated by Django 5.2.8 on 2026-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0064_printfulproducts_fancy_name_printfulproducts_tagline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfulproducts',
            name='printful_id',
            field=models.IntegerField(max_length=15, unique=True),
        ),
    ]
