# Generated by Django 5.2.8 on 2026-04-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0065_alter_printfulproducts_printful_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfulproducts',
            name='printful_id',
            field=models.DecimalField(decimal_places=0, max_digits=15, unique=True),
        ),
    ]
