# Generated by Django 5.2.8 on 2026-04-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0066_alter_printfulproducts_printful_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulproducts',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
