# Generated by Django 5.2.8 on 2026-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0067_printfulproducts_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulproducts',
            name='category_locked',
            field=models.BooleanField(default=False),
        ),
    ]
