# Generated by Django 5.2.8 on 2026-04-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0068_printfulproducts_category_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfulproducts',
            name='category_locked',
            field=models.BooleanField(default=False, verbose_name='Lock'),
        ),
    ]
