# Generated by Django 5.2.8 on 2026-04-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0069_alter_printfulproducts_category_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printfulproducts',
            name='category_locked',
        ),
    ]
