# Generated by Django 5.2.8 on 2026-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0070_remove_printfulproducts_category_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulproducts',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('pre_order', 'Pre-order'), ('sold_out', 'Sold Out')], default='published', max_length=20),
        ),
    ]
