# Generated by Django 5.2.8 on 2026-04-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0071_printfulproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulproducts',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='printfulproducts',
            name='category',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('sweatshirts', 'Sweatshirts'), ('tshirts', 'T-Shirts'), ('hats', 'Hats'), ('drink', 'Drink'), ('workspace', 'Workspace'), ('totes', 'Totes'), ('mini_dev', 'Mini Dev'), ('accessories', 'Accessories')], default='accessories', max_length=50),
        ),
    ]
