# Generated by Django 5.2.8 on 2026-04-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0072_printfulproducts_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='shipping_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
