# Generated by Django 5.2.8 on 2026-04-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0073_storeorder_shipping_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='fulfillment_status',
            field=models.CharField(choices=[('not_sent', 'Not Sent'), ('queued', 'Queued'), ('processing', 'Processing'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], default='not_sent', max_length=50),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='printful_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
