# Generated by Django 5.2.8 on 2026-05-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0074_storeorder_fulfillment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfulproducts',
            name='category',
            field=models.CharField(choices=[('hoodies', 'Hoodies'), ('sweatshirts', 'Sweatshirts'), ('tshirts', 'T-Shirts'), ('hats', 'Hats'), ('drink', 'Drink'), ('workspace', 'Workspace'), ('totes', 'Totes'), ('mini dev', 'Mini Dev'), ('accessories', 'Accessories')], default='accessories', max_length=50),
        ),
    ]
