# Generated by Django 5.2.8 on 2026-05-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0075_alter_printfulproducts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
