# Generated by Django 5.2.8 on 2026-05-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0076_alter_storeorder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='flw_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='tx_ref',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=50),
        ),
    ]
