# Generated by Django 5.2.8 on 2026-05-05 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0077_storeorder_flw_ref_storeorder_tx_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintfulVariant',
            fields=[
                ('variant_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('preview_image', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='codedly.printfulproducts')),
            ],
            options={
                'ordering': ['product', 'size', 'color'],
                'indexes': [models.Index(fields=['variant_id'], name='codedly_pri_variant_ce137c_idx'), models.Index(fields=['active'], name='codedly_pri_active_131454_idx')],
            },
        ),
    ]
