# Generated by Django 5.2.8 on 2026-05-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0078_printfulvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfulvariant',
            name='sync_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
