# Generated by Django 5.2 on 2026-05-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0079_printfulvariant_sync_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='fulfillment_response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
