# Generated by Django 5.2 on 2026-05-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codedly', '0080_storeorder_fulfillment_response'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Chrise', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/verycodedly/image/upload/v1763878238/very-codedly-banner.png', max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-created_at'], name='codedly_pos_status_0e362d_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['subcategory', 'status', '-created_at'], name='codedly_pos_subcate_b20e90_idx'),
        ),
    ]
